global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/6b01a789-90fa-4dd6-ad6d-aed16d7f3900'
          send_resolved: false