version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./rules.yml:/etc/prometheus/rules.yml
    command:
     '--config.file=/etc/prometheus/prometheus.yml'
    #network_mode: "host"
  grafana:
    image: grafana/grafana
    ports:
    - '3000:3000'
    #network_mode: "host"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
    - 9093:9093