global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 192.168.0.14:9093

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
- job_name: 'your-app'
  static_configs:
  - targets: ['192.168.0.14:3001']
- job_name: 'nodejs-app'
  static_configs:
  - targets: ['192.168.0.14:3001'] 